# ErgoArrows ZMK Config

# Bluetooth
CONFIG_ZMK_BLE=y

# Split keyboard
CONFIG_ZMK_SPLIT=y

# USB
CONFIG_ZMK_USB=y

# USB logging off (save power)
CONFIG_ZMK_USB_LOGGING=n

# Sleep after 15min idle
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# RGB LED (SK6812MINI-E / WS2812莠呈鋤)
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n

CONFIG_USB_CDC_ACM=y