# ErgoArrows ZMK Config

# Bluetooth
CONFIG_ZMK_BLE=y

# Split keyboard
CONFIG_ZMK_SPLIT=y

# USB logging off (save power)
CONFIG_ZMK_USB_LOGGING=n

# Sleep after 15min idle
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
