on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/west.yml', '**/build.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update  
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Jisplit89 Left)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=jisplit89_left
      - name: Rename left firmware
        run: cp build/zephyr/zmk.uf2 jisplit89_left.uf2
      - name: West Build (Jisplit89 Right)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=jisplit89_right  
      - name: Rename right firmware
        run: cp build/zephyr/zmk.uf2 jisplit89_right.uf2
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            jisplit89_left.uf2
            jisplit89_right.uf2
